---

name: 'Lock Threads'

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          issue-inactive-days: '90'
          pr-inactive-days: '90'
          log-output: true
          issue-comment: \n
            This issue has been automatically locked since there has \n
            not been any recent activity after it was closed.\n
            Please open a new issue for related bugs.
          pr-comment: \n
            This pull request has been automatically locked since there has \n
            not been any recent activity after it was closed.\n
            Please open a new issue for related bugs.
